// Code Generated by Sidekick is for learning and experimentation purposes only.
import { notFound } from 'next/navigation';

import Link from 'next/link';

import type { CSSProperties } from 'react';

import { getIndustryBySlug, getAllIndustrySlugs } from '@/data/industries';

import { getToolById } from '@/lib/toolsService';



export function generateStaticParams() {

  return getAllIndustrySlugs().map(slug => ({ industry: slug }));

}



const TIER: Record<string, { color: string; bg: string }> = {

  free: { color: '#059669', bg: '#ECFDF5' }, starter: { color: '#2563EB', bg: '#EFF6FF' },

  professional: { color: '#7C3AED', bg: '#F5F3FF' }, enterprise: { color: '#B45309', bg: '#FFFBEB' },

};



export default function IndustryPage({ params }: { params: { industry: string } }) {

  const ind = getIndustryBySlug(params.industry);

  if (!ind) notFound();



  return (

    <div style={{ minHeight: '100vh', background: 'var(--bg)' }}>

      {/* Hero */}

      <div style={{ background: 'var(--text-1)', color: '#fff', padding: '56px 24px 64px' }}>

        <div style={{ maxWidth: 900, margin: '0 auto' }}>

          <Link href="/industry" style={{ fontSize: 13, color: '#A1A1AA', textDecoration: 'none', display: 'inline-flex', alignItems: 'center', gap: 4, marginBottom: 24 }}>← All Industries</Link>

          <div style={{ display: 'flex', alignItems: 'flex-start', gap: 20, marginBottom: 16 }}>

            <span style={{ fontSize: 56 }}>{ind.emoji}</span>

            <div>

              <h1 style={{ fontFamily: "'Plus Jakarta Sans', sans-serif", fontSize: 'clamp(32px, 4vw, 48px)', fontWeight: 800, letterSpacing: '-0.04em', marginBottom: 8 }}>{ind.name}</h1>

              <p style={{ fontSize: 18, color: '#A1A1AA' }}>{ind.tagline}</p>

            </div>

          </div>

          <p style={{ fontSize: 15, color: '#D4D4D8', lineHeight: 1.7, maxWidth: 700 }}>{ind.description}</p>

        </div>

      </div>



      <div style={{ maxWidth: 900, margin: '0 auto', padding: '56px 24px' }}>

        {/* Compliance */}

        {ind.complianceRequirements.length > 0 && (

          <section style={{ marginBottom: 56 }}>

            <h2 style={{ fontSize: 26, fontWeight: 800, letterSpacing: '-0.03em', marginBottom: 6 }}>Compliance Requirements</h2>

            <p style={{ fontSize: 15, color: 'var(--text-2)', marginBottom: 24 }}>Every tool in your stack must support these.</p>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: 14 }}>

              {ind.complianceRequirements.map(r => (

                <div key={r.name} style={{ background: r.critical ? '#FEF2F2' : 'var(--surface)', border: `1px solid ${r.critical ? '#FECACA' : 'var(--border)'}`, borderRadius: 10, padding: 18 }}>

                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>

                    <span style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.04em', color: r.critical ? '#DC2626' : 'var(--text-3)', background: r.critical ? '#FEE2E2' : 'var(--bg)', padding: '3px 8px', borderRadius: 99 }}>{r.critical ? 'REQUIRED' : 'RECOMMENDED'}</span>

                    <span style={{ fontWeight: 700, fontSize: 15 }}>{r.name}</span>

                  </div>

                  <p style={{ fontSize: 13, color: r.critical ? '#991B1B' : 'var(--text-2)', lineHeight: 1.6 }}>{r.description}</p>

                </div>

              ))}

            </div>

          </section>

        )}



        {/* Pain Points */}

        <section style={{ marginBottom: 56 }}>

          <h2 style={{ fontSize: 26, fontWeight: 800, letterSpacing: '-0.03em', marginBottom: 24 }}>Common Pain Points</h2>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 12 }}>

            {ind.painPoints.map((p, i) => (

              <div key={i} style={{ display: 'flex', gap: 12, background: '#FFFBEB', border: '1px solid #FDE68A', borderRadius: 10, padding: '14px 16px' }}>

                <span style={{ flexShrink: 0, fontSize: 16 }}>⚠️</span>

                <span style={{ fontSize: 14, color: '#92400E', lineHeight: 1.55 }}>{p}</span>

              </div>

            ))}

          </div>

        </section>



        {/* Stacks */}

        <section style={{ marginBottom: 56 }}>

          <h2 style={{ fontSize: 26, fontWeight: 800, letterSpacing: '-0.03em', marginBottom: 6 }}>Recommended Stacks</h2>

          <p style={{ fontSize: 15, color: 'var(--text-2)', marginBottom: 28 }}>Curated combinations that work well together.</p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>

            {ind.stacks.map(stack => {

              const stackTools = stack.toolIds.map(id => getToolById(id)).filter(Boolean);

              return (

                <div key={stack.label} style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12, padding: 28, boxShadow: 'var(--shadow-sm)' }}>

                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 }}>

                    <h3 style={{ fontSize: 20, fontWeight: 700, letterSpacing: '-0.02em' }}>{stack.label}</h3>

                    <span style={{ fontSize: 12, color: 'var(--text-3)', background: 'var(--bg)', border: '1px solid var(--border)', padding: '4px 10px', borderRadius: 99 }}>{stack.companySize}</span>

                  </div>

                  <p style={{ fontSize: 14, color: 'var(--text-2)', lineHeight: 1.65, marginBottom: 20 }}>{stack.description}</p>

                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 10 }}>

                    {stackTools.map(tool => {

                      if (!tool) return null;

                      const t = TIER[tool.pricingTier] ?? TIER.professional;

                      return (

                        <Link key={tool.id} href={`/tools/${tool.id}`} style={{ textDecoration: 'none' }}>

                          <div className="stack-tool-card" style={{ background: 'var(--bg)', border: '1px solid var(--border)', borderRadius: 8, padding: '12px 14px', transition: 'border-color 0.15s' }}>

                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 4 }}>

                              <span style={{ fontWeight: 700, fontSize: 13, color: 'var(--text-1)' }}>{tool.name}</span>

                              <span style={{ fontSize: 10, fontWeight: 700, color: t.color, background: t.bg, padding: '1px 6px', borderRadius: 99, marginLeft: 4 }}>{tool.pricingTier}</span>

                            </div>

                            <p style={{ fontSize: 11, color: 'var(--text-3)', overflow: 'hidden', display: '-webkit-box', WebkitLineClamp: 1, WebkitBoxOrient: 'vertical' } as CSSProperties}>{tool.description}</p>

                          </div>

                        </Link>

                      );

                    })}

                  </div>

                  <Link href={`/stack-builder?preload=${stack.toolIds.join(',')}`} style={{ display: 'inline-block', marginTop: 16, fontSize: 13, fontWeight: 600, color: 'var(--accent)', textDecoration: 'none' }}>

                    Build on this stack →

                  </Link>

                </div>

              );

            })}

          </div>

        </section>



        {/* Avoid */}

        {ind.avoidTools.length > 0 && (

          <section style={{ marginBottom: 56 }}>

            <h2 style={{ fontSize: 26, fontWeight: 800, letterSpacing: '-0.03em', marginBottom: 6 }}>Approach with Caution</h2>

            <p style={{ fontSize: 15, color: 'var(--text-2)', marginBottom: 20 }}>Popular tools that often disappoint {ind.name.toLowerCase()} teams.</p>

            {ind.avoidTools.map(({ toolId, reason }) => {

              const tool = getToolById(toolId);

              if (!tool) return null;

              return (

                <div key={toolId} style={{ display: 'flex', gap: 14, background: '#FFF7ED', border: '1px solid #FED7AA', borderRadius: 10, padding: '16px 20px', marginBottom: 10 }}>

                  <span style={{ fontSize: 18, flexShrink: 0 }}>⚠️</span>

                  <div style={{ fontSize: 14, color: '#9A3412', lineHeight: 1.6 }}>

                    <strong>{tool.name}:</strong> {reason}

                  </div>

                </div>

              );

            })}

          </section>

        )}



        {/* CTA */}

        <div style={{ background: 'var(--accent)', borderRadius: 14, padding: '40px 36px', textAlign: 'center' }}>

          <h3 style={{ fontFamily: "'Plus Jakarta Sans', sans-serif", fontSize: 24, fontWeight: 800, color: '#fff', letterSpacing: '-0.03em', marginBottom: 8 }}>Need a personalized recommendation?</h3>

          <p style={{ fontSize: 15, color: 'rgba(255,255,255,0.8)', marginBottom: 24 }}>Describe your exact situation and our AI advisor will recommend the right stack.</p>

          <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>

            <Link href={`/chat?context=${encodeURIComponent(`I work in ${ind.name}`)}`} style={{ background: '#fff', color: 'var(--accent)', padding: '11px 24px', borderRadius: 8, fontSize: 14, fontWeight: 700, textDecoration: 'none', fontFamily: "'Plus Jakarta Sans', sans-serif" }}>

              Chat with AI Advisor →

            </Link>

            <Link href="/quiz" style={{ background: 'rgba(255,255,255,0.15)', color: '#fff', padding: '11px 24px', borderRadius: 8, fontSize: 14, fontWeight: 600, textDecoration: 'none', border: '1px solid rgba(255,255,255,0.3)' }}>

              Take the Quiz

            </Link>

          </div>

        </div>

      </div>

      <style>{`
        .stack-tool-card:hover {
          border-color: var(--accent-mid) !important;
        }
      `}</style>

    </div>

  );

}
